# Generated by Django 3.1.4 on 2021-11-17 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snack',
            new_name='Roses',
        ),
    ]
